export const goods = (function () {
    return [
        {
            commodityId: 1,
            productionName: '商标设计',
            goodsName: '文字商标设计',
            goodsAttr: '文字商标设计',
            goodsAddr: '深圳市',
            goodsPrice: 1500,
            goodsPeriod: '1',
            goodsType: '普通产品',
            bookkeepingDateAfter: '',
            bookkeepingDateBegin: '',
            commodityAmount: 1500,
            handselDate: 0,
            number: 1,
            date: ['', '']
        },
        {
            commodityId: 2,
            productionName: '外资公司注销',
            goodsName: '外资公司注销 常规注销',
            goodsAttr: '常规注销',
            goodsAddr: '深圳市',
            goodsPrice: 12000,
            goodsPeriod: '1',
            goodsType: '普通产品',
            bookkeepingDateAfter: '',
            bookkeepingDateBegin: '',
            commodityAmount: 12000,
            handselDate: 0,
            number: 1,
            date: ['', '']
        },
        {
            commodityId: 3,
            productionName: '公司注册基础套餐',
            goodsName: '公司注册基础套餐',
            goodsAttr: '',
            goodsAddr: '深圳市',
            goodsPrice: 3600,
            goodsPeriod: '1',
            goodsType: '套餐',
            bookkeepingDateAfter: '',
            bookkeepingDateBegin: '',
            commodityAmount: 3600,
            handselDate: 0,
            number: 1,
            date: ['', '']
        },
        {
            commodityId: 4,
            productionName: '地址变更基础套餐',
            goodsName: '地址变更基础套餐',
            goodsAttr: '',
            goodsAddr: '深圳市',
            goodsPrice: 1200,
            goodsPeriod: '1',
            goodsType: '套餐',
            bookkeepingDateAfter: '',
            bookkeepingDateBegin: '',
            commodityAmount: 1200,
            handselDate: 0,
            number: 1,
            date: ['', '']
        },
        {
            commodityId: 5,
            productionName: '商标复审/转让/续期',
            goodsName: '商标复审',
            goodsAttr: '商标复审',
            goodsAddr: '广州市',
            goodsPrice: 5500,
            goodsPeriod: '1',
            goodsType: '普通产品',
            bookkeepingDateAfter: '',
            bookkeepingDateBegin: '',
            commodityAmount: 5500,
            handselDate: 0,
            number: 1,
            date: ['', '']
        },
    ]
})()